on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v3.4.1
      with:
        distribution: 'temurin'
        java-version: 8
        cache: maven

    - run: mvn test
